package attendancemgt;

import javax.swing.*;
import java.awt.*;
import java.awt.print.*;
import java.io.*;
import java.nio.charset.StandardCharsets;

/**
 * Utility class for exporting reports to PDF (via print), Excel (CSV), and Print.
 * Uses only Java built-in APIs - no external libraries needed.
 */
public class ReportExporter {

    private static final Color HEADER_BG = new Color(52, 73, 94);
    private static final Color WHITE = Color.WHITE;
    private static final Color TEXT_COLOR = new Color(44, 62, 80);
    private static final Color SUCCESS = new Color(39, 174, 96);
    private static final Color DANGER = new Color(192, 57, 43);
    private static final Color WARNING = new Color(243, 156, 18);

    /**
     * Exports the table data to Printer or PDF (via "Save as PDF" in print dialog).
     */
    public static void exportToPrint(JFrame parentFrame, String[][] records, String[] headers,
                                      String title, String subtitle) {
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName(title);

        Printable printable = (graphics, pageFormat, pageIndex) -> {
            if (pageIndex > 0) return Printable.NO_SUCH_PAGE;

            Graphics2D g2d = (Graphics2D) graphics;
            g2d.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                    RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

            double pageWidth = pageFormat.getImageableWidth();
            double pageHeight = pageFormat.getImageableHeight();
            double x = pageFormat.getImageableX();
            double y = pageFormat.getImageableY();

            // Title
            g2d.setFont(new Font("Segoe UI", Font.BOLD, 16));
            g2d.setColor(TEXT_COLOR);
            g2d.drawString(title, (int) x + 20, (int) y + 30);

            // Subtitle
            g2d.setFont(new Font("Segoe UI", Font.PLAIN, 11));
            g2d.setColor(new Color(120, 120, 120));
            g2d.drawString(subtitle, (int) x + 20, (int) y + 48);

            // Divider line
            g2d.setColor(new Color(200, 200, 200));
            g2d.drawLine((int) x + 20, (int) y + 55, (int) (x + pageWidth - 20), (int) y + 55);

            // Table headers
            int colCount = Math.min(headers.length, 8);
            int[] colWidths = {30, 80, 80, 150, 50, 150, 70, 70};
            // Recalculate based on available width
            int totalW = (int) pageWidth - 40;
            for (int i = 0; i < colCount; i++) {
                colWidths[i] = totalW / colCount;
            }

            int rowY = 70;
            int rowH = 22;
            int startX = (int) x + 20;

            // Draw header
            g2d.setFont(new Font("Segoe UI", Font.BOLD, 9));
            g2d.setColor(HEADER_BG);
            g2d.fillRect(startX, rowY, totalW, rowH);
            g2d.setColor(WHITE);
            int colX = startX;
            for (int i = 0; i < colCount; i++) {
                String hText = i < headers.length ? headers[i] : "";
                g2d.drawString(hText, colX + 3, rowY + 15);
                colX += colWidths[i];
            }

            // Draw rows
            rowY += rowH;
            g2d.setFont(new Font("Segoe UI", Font.PLAIN, 8));
            int maxRows = (int) ((pageHeight - rowY - 20) / rowH);
            maxRows = Math.min(maxRows, records.length);

            for (int r = 0; r < maxRows && r < records.length; r++) {
                colX = startX;
                // Alternate row background
                if (r % 2 == 0) {
                    g2d.setColor(new Color(245, 245, 245));
                    g2d.fillRect(startX, rowY, totalW, rowH);
                }

                for (int c = 0; c < colCount && c < records[r].length; c++) {
                    String text = records[r][c];
                    // Remove emojis for print
                    text = text.replaceAll("[\\u2705\\u274C\\u23F0]", "");
                    text = text.trim();

                    g2d.setColor(TEXT_COLOR);
                    g2d.drawString(text, colX + 3, rowY + 14);
                    colX += colWidths[c];
                }
                rowY += rowH;
            }

            // Footer
            g2d.setColor(new Color(150, 150, 150));
            g2d.setFont(new Font("Segoe UI", Font.PLAIN, 8));
            g2d.drawString("Generated by Attendance Management System | Page " + (pageIndex + 1),
                    (int) x + 20, (int) (y + pageHeight - 10));

            // Summary at bottom
            int presentCount = 0, absentCount = 0, lateCount = 0;
            for (String[] rec : records) {
                String status = rec.length > 6 ? rec[6] : "";
                if (status.contains("Present")) presentCount++;
                else if (status.contains("Absent")) absentCount++;
                else if (status.contains("Late")) lateCount++;
            }

            rowY += 15;
            g2d.setFont(new Font("Segoe UI", Font.BOLD, 10));
            g2d.setColor(TEXT_COLOR);
            g2d.drawString("Summary:", startX, rowY);
            rowY += 14;
            g2d.setFont(new Font("Segoe UI", Font.PLAIN, 9));
            g2d.setColor(SUCCESS);
            g2d.drawString("Present: " + presentCount, startX + 10, rowY);
            g2d.setColor(DANGER);
            g2d.drawString("  Absent: " + absentCount, startX + 100, rowY);
            g2d.setColor(WARNING);
            g2d.drawString("  Late: " + lateCount, startX + 200, rowY);
            g2d.setColor(TEXT_COLOR);
            g2d.drawString("  Total: " + records.length, startX + 300, rowY);

            return Printable.PAGE_EXISTS;
        };

        job.setPrintable(printable);

        if (job.printDialog()) {
            try {
                job.print();
                JOptionPane.showMessageDialog(parentFrame,
                        "<html><b style='color:#27ae60'>Report sent to printer/PDF successfully!</b></html>",
                        "Print Success", JOptionPane.INFORMATION_MESSAGE);
            } catch (PrinterException ex) {
                JOptionPane.showMessageDialog(parentFrame,
                        "<html><b style='color:#e74c3c'>Printing failed:</b><br>" + ex.getMessage() + "</html>",
                        "Print Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Exports table data to CSV file that can be opened in Excel.
     */
    public static void exportToCSV(JFrame parentFrame, String[][] records, String[] headers,
                                    String fileName, String title) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Export to Excel (CSV)");
        fileChooser.setSelectedFile(new File(fileName + ".csv"));

        int result = fileChooser.showSaveDialog(parentFrame);
        if (result != JFileChooser.APPROVE_OPTION) return;

        File file = fileChooser.getSelectedFile();
        if (!file.getName().toLowerCase().endsWith(".csv")) {
            file = new File(file.getAbsolutePath() + ".csv");
        }

        try (OutputStreamWriter writer = new OutputStreamWriter(
                new FileOutputStream(file), StandardCharsets.UTF_8)) {

            // Write BOM for Excel to recognize UTF-8
            writer.write('\uFEFF');

            // Write title
            writer.write("\"" + title + "\"");
            writer.write("\n");

            // Write headers
            for (int i = 0; i < headers.length; i++) {
                writer.write("\"" + headers[i] + "\"");
                if (i < headers.length - 1) writer.write(",");
            }
            writer.write("\n");

            // Write data rows
            for (String[] record : records) {
                for (int i = 0; i < record.length; i++) {
                    String cell = record[i]
                            .replace("\u2705 Present", "Present")
                            .replace("\u274C Absent", "Absent")
                            .replace("\u23F0 Late", "Late")
                            .replace("\"", "\"\"");
                    writer.write("\"" + cell + "\"");
                    if (i < record.length - 1) writer.write(",");
                }
                writer.write("\n");
            }

            // Summary row
            int presentCount = 0, absentCount = 0, lateCount = 0;
            for (String[] rec : records) {
                String status = rec.length > 6 ? rec[6] : "";
                if (status.contains("Present")) presentCount++;
                else if (status.contains("Absent")) absentCount++;
                else if (status.contains("Late")) lateCount++;
            }
            writer.write("\n");
            writer.write("\"Summary,,,,Present: " + presentCount
                    + ",Absent: " + absentCount
                    + ",Late: " + lateCount
                    + ",Total: " + records.length + "\"");

            writer.flush();

            JOptionPane.showMessageDialog(parentFrame,
                    "<html><b style='color:#27ae60'>Excel file saved successfully!</b><br>"
                    + "Location: " + file.getAbsolutePath() + "</html>",
                    "Export Complete", JOptionPane.INFORMATION_MESSAGE);

            // Open the file
            try {
                Desktop.getDesktop().open(file);
            } catch (Exception ignored) {
                // User can open manually
            }

        } catch (IOException ex) {
            JOptionPane.showMessageDialog(parentFrame,
                    "<html><b style='color:#e74c3c'>Could not save file:</b><br>" + ex.getMessage() + "</html>",
                    "Export Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Opens the standard print dialog for a JTable or component.
     */
    public static void exportToPrintDialog(JFrame parentFrame, Component component, String title) {
        try {
            PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName(title);

            job.printDialog();
            // For printable content, use the Printable-based method instead
            JOptionPane.showMessageDialog(parentFrame,
                    "<html><b style='color:#27ae60'>Print dialog opened.</b><br>"
                    + "Use the Report Export buttons on this page for structured printing.</html>",
                    "Print", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(parentFrame,
                    "<html><b style='color:#e74c3c'>Print error:</b><br>" + ex.getMessage() + "</html>",
                    "Print Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}

